---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Set default incoming policy
  community.general.ufw:
    direction: incoming
    policy: "{{ ufw_default_incoming }}"

- name: Set default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: "{{ ufw_default_outgoing }}"

- name: Allow configured TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_open_tcp_ports }}"

- name: Allow configured UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ ufw_open_udp_ports }}"

- name: Enable ufw
  community.general.ufw:
    state: enabled
