---
unattended_upgrades_origins:
  - 'origin=Debian,codename=${distro_codename},label=Debian-Security'
  - 'origin=Debian,codename=${distro_codename},label=Debian'
  - 'origin=Debian,codename=${distro_codename}-updates,label=Debian'
