---
ssh_allow_users:
  - "{{ server_admin_user }}"
ssh_max_auth_tries: 3
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 8
ssh_use_pam: true
ssh_allow_tcp_forwarding: true
ssh_password_authentication: false
ssh_permit_root_login: "no"

ssh_listen_address: 0.0.0.0
