---
- name: Configure BBR sysctl settings
  ansible.builtin.copy:
    dest: "{{ sysctl_bbr_conf_path }}"
    owner: root
    group: root
    mode: '0644'
    content: |
      net.core.default_qdisc=fq
      net.ipv4.tcp_congestion_control=bbr
  register: bbr_sysctl_conf

- name: Reload sysctl configuration
  ansible.builtin.command: sysctl --system
  when: bbr_sysctl_conf is changed
  changed_when: true
